### ISSUE TITLE
permision error on v1.1.8

### ISSUE THREAD

**Issue by masterwishx** [xavier-hernandez/goaccess-for-nginxproxymanager#103]
having error after last update, added puid,guid 99,100 or 0,0 not helped  :

![image png f1de26785a6074d69d4f943c3d9008f6](https://user-images.githubusercontent.com/28630321/192720303-930a4495-af73-4af5-b407-6628c30ff0d3.png)

**Comment by kaasszje** [comment]
Having the same issue, downgraded to v1.1.7

**Comment by Reupireup** [comment]
same here

**Comment by xavier-hernandez** [comment]
@masterwishx @kaasszje @Reupireup I've fixed this issue. Please grab the latest again. Somehow during the merge process the execute flag was removed from start.sh. I'll modify the dockerfile so this doesn't happen again.

**Comment by kaasszje** [comment]
Works again :) thank you for the fast fix :)

**Comment by masterwishx** [comment]
@xavier-hernandez Thanks for fast fix , working fine
