### ISSUE TITLE
No archived logs found at /opt/log

### ISSUE THREAD

**Issue by leon1995** [xavier-hernandez/goaccess-for-nginxproxymanager#106]
Hi,

I get the error `No archived logs found at /opt/log`. I do noticed, that the logs are not contained in the container, because `$ docker-compose exec goaccess ls /opt/log` do not show me any log file. I have mapped the volume in my `docker-compose.yml` like this
```
 volumes:
        - ./data/logs:/opt/log
```
On my host, there are plenty of files in `data/logs`

**Comment by xavier-hernandez** [comment]
@leon1995 are there any other errors shown? Can you send me a screenshot of the output when running the container?

Thanks.

**Comment by leon1995** [comment]
no, there arent any errors. here is the output with debug `True`:
```
goaccess     | 
goaccess     | GOAN v1.1.8
goaccess     | 
goaccess     | 
goaccess     | NGINX SETUP...
goaccess     | 
goaccess     | NGINX BASIC AUTH
goaccess     | -------------------------------
goaccess     | None
goaccess     | 
goaccess     | 
goaccess     | NPM INSTANCE SETTING UP...
goaccess     | 
goaccess     | LOADING NPM PROXY LOGS
goaccess     | -------------------------------
goaccess     | 
goaccess     |  Adding proxy logs...
goaccess     |  Found (0) proxy logs...
goaccess     | 
goaccess     |  SKIP ARCHIVED LOGS
goaccess     |  -------------------------------
goaccess     |  FALSE
goaccess     |  No archived logs found at /opt/log...
goaccess     | 
goaccess     | EXCLUDE IPS
goaccess     | -------------------------------
goaccess     | 127.0.0.1
goaccess     | 
goaccess     | Setting GeoIP Database
goaccess     | -------------------------------
goaccess     | DEFAULT
goaccess     | 
goaccess     | DEBUG
goaccess     | -------------------------------
goaccess     | OFF
goaccess     | 
goaccess     | RUN NPM GOACCESS
goaccess     | 
WebSocket server ready to accept new client connections
```

and I can understand, there he cannot find any logs, because it seems that they arent copied to the docker container. But I dont know why, because I set up the directory mapping...

**Comment by xavier-hernandez** [comment]
@leon1995 you are correct the logs are not copied into the container. Can you try referencing the entire directory rather than just ./data/logs ?

**Comment by leon1995** [comment]
What do you mean exactly?

**Comment by xavier-hernandez** [comment]
/root/something/npm/data/logs

**Comment by leon1995** [comment]
not working. I know that `./data/...` works, because I use it also on other services

**Comment by leon1995** [comment]
also it says that
```
goaccess     | DEBUG
goaccess     | -------------------------------
goaccess     | OFF
```
but I have `DEBUG=True` set

**Comment by xavier-hernandez** [comment]
can you provide your docker compose file so I can look that over?

**Comment by leon1995** [comment]
```
version: '3'
services:
  app:
    image: 'baudneo/nginx-proxy-manager:latest'
    container_name: app
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      # crowdsec censored stuff
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt/
    restart: always

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

# crowdsec stuff

  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: always
    environment:
        - TZ=Europe/Berlin
        - SKIP_ARCHIVED_LOGS=False #optional
        - DEBUG=True #optional
        - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited list    
        - LOG_TYPE=NPM #optional - more information below            
    ports:
        - '7880:7880'
    volumes:
        - ./data/logs:/opt/log/
```

**Comment by xavier-hernandez** [comment]
Looks right. So if you go to ./data/logs you see log files?

Maybe try adding this to goaccess but that shouldn't matter if the files are already there.

depends_on:
      - app

**Comment by leon1995** [comment]
Yes there are 301 files in `./data/logs`...

I added the depends_on but it didnt work

**Comment by Sperryfreak01** [comment]
Having a similar issue.  If I jump into the containers console I can tail output the log files bind mounted into /opt/logs.  Haven't figured out anything else yet.

**Comment by xavier-hernandez** [comment]
@leon1995 or @Sperryfreak01 any luck with this?

**Comment by Sperryfreak01** [comment]
I'll be honest I forgot what this was and what I was trying to do.

**Comment by leon1995** [comment]
No... but it would be nice if there was a solution...

**Comment by xavier-hernandez** [comment]
@leon1995 what I've somewhat learned is that sometimes GoAccess silently discards logs starting with errors. Can you send me a sample of the logs? Post them on PasteBin or something similar.

**Comment by leon1995** [comment]
I habe updated the docker container and now the log files are found and everything looks fine!
