### ISSUE TITLE
All panels

### ISSUE THREAD

**Issue by taimadoCE** [xavier-hernandez/goaccess-for-nginxproxymanager#112]
Hi, @xavier-hernandez Why don't you consider put all the panels available to permit to choose? 

![imagen](https://user-images.githubusercontent.com/57089805/204132354-7b924f61-17de-403a-853f-b6545ddba1a2.png)

**Comment by xavier-hernandez** [comment]
@taimadoCE all the panels are available, I think. Unless you see one missing. The additional one you found for TLS needs a setup before it displays.

**Comment by xavier-hernandez** [comment]
Closing this... All panels are showing except for TLS which needs manual implementation.
