### ISSUE TITLE
New ASN Panel

### ISSUE THREAD

**Issue by taimadoCE** [xavier-hernandez/goaccess-for-nginxproxymanager#122]
Hi, @xavier-hernandez Have you try if the new ASN panel works on your configs? I'd like to know if there is a way to manage it or something to work properly...
![imagen](https://user-images.githubusercontent.com/57089805/212146409-cab6dfd2-d418-44f7-a535-d4cf43cded7b.png)

**Comment by xavier-hernandez** [comment]
Thanks for catching this. It appears that I need an additional maxmind database for ASN. Give me 2-3 days to get this done.

**Comment by xavier-hernandez** [comment]
@taimadoCE this has been completed.
