### ISSUE TITLE
About protocol version info & charts

### ISSUE THREAD

**Issue by taimadoCE** [xavier-hernandez/goaccess-for-nginxproxymanager#129]
Hi again, @xavier-hernandez One question. Is it possible to add to the charts the protocol info as you can see in the live demo of official goaccess?

![imagen](https://user-images.githubusercontent.com/57089805/213985269-55827b10-eaef-4f2a-bd85-9514d9c2c5f5.png)

**Comment by xavier-hernandez** [comment]
@taimadoCE this doesn't look possible for NPM logs. The protocol just appears to be available in the error logs but I'll keep an eye on this.

**Comment by xavier-hernandez** [comment]
Closing this for now because this information doesn't seem to be available on the proxy hosts.
