### ISSUE TITLE
IPv6 addresses are showing up as unknown 

### ISSUE THREAD

**Issue by Albonycal** [xavier-hernandez/goaccess-for-nginxproxymanager#135]
Any traffic coming from an IPv6 address doesn't show up in the web interface and it says "unknown" 
![image](https://user-images.githubusercontent.com/67057319/221340568-8140fed4-9df6-4600-90ee-01ed772ec61a.png)

**Comment by xavier-hernandez** [comment]
Can you provide me a snippet of your logs?

**Comment by xavier-hernandez** [comment]
Would you be able to upload a sample log here https://goan.portal.massive.app ? On my end it works for small sample file that used Google and CloudFlare IPv6 addresses. I'm not sure what "unknown" would mean on your end without the log file.

**Comment by Albonycal** [comment]
My bad, that was just due to me using Cloudflare proxy :D sorry for bothering you
