### ISSUE TITLE
Custom Date Range

### ISSUE THREAD

**Issue by HaveSomeBugs** [xavier-hernandez/goaccess-for-nginxproxymanager#14]
Is there any way to allow for custom date ranges? Sometimes I only want to see the data for the last week/month/quarter/year etc.

**Comment by xavier-hernandez** [comment]
This is an issue with GoAcccess but it seems like they are working on it. I do have an issue open on this project to provide an option to not load the archived logs but I'm guessing your looking at this via a GUI perspective. Filtering your date ranges. 

Please close this if that answers your question. Thanks!

https://github.com/allinurl/goaccess/issues/478
https://github.com/allinurl/goaccess/issues/117
