### ISSUE TITLE
Dashboard settings: date interval

### ISSUE THREAD

**Issue by jeanpaulrh** [xavier-hernandez/goaccess-for-nginxproxymanager#143]
Hi, and sorry for the silly question.
Is there a way to set a different time interval for the data displayed in the dashboard? i.e. last month, last week, last n months.
Thanks and have a nice day.

**Comment by xavier-hernandez** [comment]
@jeanpaulrh sorry thought I answered you. There currently is not but I believe is in development by GoAccess. Please refer to https://github.com/allinurl/goaccess/issues/117

There is a limited way I can do it on my end but it would require a restart of the container every day which would not be helpful.
