### ISSUE TITLE
If using boolean don't work SKIP_ARCHIVED_LOGS

### ISSUE THREAD

**Issue by webysther** [xavier-hernandez/goaccess-for-nginxproxymanager#146]
Works:

```sh
...
SKIP_ARCHIVED_LOGS: "True"
```

Don't

```sh
...
SKIP_ARCHIVED_LOGS: True
```

The check in the code is case-sensitive, when using boolean in docker compose the "True" is converted to "true".

**Comment by xavier-hernandez** [comment]
@webysther I'll correct that by the end of the month

**Comment by xavier-hernandez** [comment]
Fixed.
