### ISSUE TITLE
No reading logs after v1.1.13

### ISSUE THREAD

**Issue by ljpaff** [xavier-hernandez/goaccess-for-nginxproxymanager#149]
Hi friends,

after v1.1.13 goaccess can't read log files:

NPM INSTANCE SETTING UP...

LOADING NPM PROXY LOGS
-------------------------------

	Adding proxy logs...
	File /opt/log/proxy-host-6_access.log does not exist
	Found (0) proxy logs...

	SKIP ARCHIVED LOGS
	-------------------------------
	FALSE

	Adding proxy archive logs...
	File /opt/log/proxy-host-6_access.log.1.gz does not exist
	File /opt/log/proxy-host-6_access.log.3.gz does not exist
	File /opt/log/proxy-host-6_access.log.2.gz does not exist

	Added (0) proxy archived logs from /opt/log...

EXCLUDE IPS
-------------------------------
127.0.0.1

Setting GeoIP Database
-------------------------------
DEFAULT

DEBUG
-------------------------------
OFF

RUN NPM GOACCESS
 [SETTING UP STORAGE /goaccess-config/active.log] {0} @ {0/s}
WebSocket server ready to accept new client connections

This is my docker-container goaccess part:

  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:v1.1.14
    container_name: goaccess
    restart: unless-stopped
    volumes:
        - /opt/nginx_proxy/data/logs:/opt/log
    ports:
        - '7880:7880'
    environment:
        - PUID=0
        - PGID=0
        - TZ=Europe/Madrid    
        - SKIP_ARCHIVED_LOGS=False #optional
        - BASIC_AUTH=True #optional
        - BASIC_AUTH_USERNAME=xxxxxxx #optional
        - BASIC_AUTH_PASSWORD=xxxxxxxx #optional
        - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited     
        - LOG_TYPE=NPM
        - INCLUDE_PROXY_HOSTS=6
    depends_on:
        - app

This is my /opt/log mounted filesystem:

![image](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/assets/27012839/2cb72399-c13e-476b-86ad-de49e3bdda83)

**Comment by supermamon** [comment]
+1

**Comment by xavier-hernandez** [comment]
@ljpaff and @supermamon can you pull the develop version? I've made some updates.

docker pull xavierh/goaccess-for-nginxproxymanager:develop

**Comment by supermamon** [comment]
I now get a bunch of `exists but is not readable`.

Things I tried:

* with and without PGID/PUID - both shows the same error
* `docker exec -it goaccess sh` and `cat '/opt/log/proxy-host-7_access.log'` which shows content

```
goaccess    | NPM INSTANCE SETTING UP...
goaccess    | 
goaccess    | LOADING NPM PROXY LOGS
goaccess    | -------------------------------
goaccess    | 
goaccess    | 	Adding proxy logs...
goaccess    | \tDebug2=/opt/log/proxy-host-4_access.log
goaccess    | 	File /opt/log/proxy-host-4_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-43_access.log
goaccess    | 	File /opt/log/proxy-host-43_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-57_access.log
goaccess    | 	File /opt/log/proxy-host-57_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-75_access.log
goaccess    | 	File /opt/log/proxy-host-75_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-66_access.log
goaccess    | 	File /opt/log/proxy-host-66_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-31_access.log
goaccess    | 	File /opt/log/proxy-host-31_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-87_access.log
goaccess    | 	File /opt/log/proxy-host-87_access.log exists but is not readable
goaccess    | \tDebug2=/opt/log/proxy-host-1_access.log
```

**Comment by xavier-hernandez** [comment]
@supermamon what OS and architecture are you using?

**Comment by supermamon** [comment]
Raspberry Pi OS

uname: `Linux rpi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux`
docker: `version 19.03.13, build 4484c46`

**Comment by xavier-hernandez** [comment]
@supermamon I've removed the readable check. I know I had an issue a while back reading files in ARM but I thought that was corrected but guess not.

Can you pull the image again and see if it loads the data? docker pull xavierh/goaccess-for-nginxproxymanager:develop

**Comment by supermamon** [comment]
That worked! Thanks!

**Comment by xavier-hernandez** [comment]
@supermamon so it does display data?

**Comment by supermamon** [comment]
yes it does. 

![image](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/assets/6381508/e2678714-e1c5-4ef3-affd-7379c1653986)

**Comment by ljpaff** [comment]
Hi, excuse me for being late.

With Develop branch i still have same problem. I'm using raspberry pi 4 with **Linux proxyserver 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux** . It is a 32bit OS.

![image](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/assets/27012839/4e651376-c424-4380-885c-a759c0890304)


I'm using the INCLUDE_PROXY_HOSTS option:

![image](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/assets/27012839/b9d7686e-e0b3-432d-b2e4-afc779881d6c)

**Comment by xavier-hernandez** [comment]
This is now available in latest.
