### ISSUE TITLE
missing 1st letter of DATA in REQUESTED FILES (URLS) on error page

### ISSUE THREAD

**Issue by Gerben-W** [xavier-hernandez/goaccess-for-nginxproxymanager#153]
On the localhost:7880/error page the 1st letter of the data within the REQUESTED FILES (URLS) panel are missing.

**Comment by robertalexa** [comment]
Same here. Attached screenshot - redacted
![image](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/assets/9019306/105dc2e1-8391-4134-b35d-f88b6cded809)

**Comment by xavier-hernandez** [comment]
This has been corrected in xavierh/goaccess-for-nginxproxymanager:develop. It should be in the latest tag within the week. Actually, it wasn't even showing the correct information.

**Comment by xavier-hernandez** [comment]
Fixed in v1.1.25
