### ISSUE TITLE
Goaccess stops at loading 208

### ISSUE THREAD

**Issue by comfuzio** [xavier-hernandez/goaccess-for-nginxproxymanager#155]
Hi!
I have NPM in my portainer with this setup in docker-compose.yml
`version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt`

I wanted to add the goaccess so i can get some stats etc and I have asked chat gpt to guide me on how to use both, the code I ended up with is

`version: '3.3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  goaccess:
    image: 'xavierh/goaccess-for-nginxproxymanager:latest'
    container_name: goaccess
    restart: always
    ports:
      - '7880:7880'
    environment:
      - PUID=0         # Set to the User ID with read access to the log files (e.g., 0 for root)
      - PGID=0         # Set to the Group ID with read access to the log files (e.g., 0 for root)
      - TZ=Europe/Athens         
      - SKIP_ARCHIVED_LOGS=False # optional
      - DEBUG=False # optional
      - BASIC_AUTH=False # optional
      - BASIC_AUTH_USERNAME=user # optional
      - BASIC_AUTH_PASSWORD=pass # optional   
      - EXCLUDE_IPS=127.0.0.1 # optional - comma delimited 
      - LOG_TYPE=NPM # optional - more information below
    volumes:
      - ./data/logs:/opt/log
`

I can deploy it and it runs, I didn't lose access to my NPM and all websites work as they should but when i go to http://my-internal-staticip:7880
I see:
GOAN 1.1.18
Loading...
Logs processing: 208 (might take some time depending on the number of files to parse)

it autorefreshes but remains at 208 forever. At first I thought this could be because the NPM was running for like a year and logs could be big but the system is on NVMe storage, 12 core cpu and plenty of ram, so it wouldn't take this long.
Now I am not an expert on docker or portainer and chat gpt has been wrong in many things, can someone point out where have I done wrong and how to fix it? 

Thanks!

**Comment by xavier-hernandez** [comment]
In NPM can you make sure that you have "websockets support" on.

**Comment by comfuzio** [comment]
What do you mean with websockers support on? I do not have in NPM any link to view it, i just go by IP:port

**Comment by xavier-hernandez** [comment]
oh sorry, I thought you were using NPM to access GOAN. But it seems like your problem is direct. Ummm those your config end with that ` ? or is that just a copy and paste issue?

volumes:
- ./data/logs:/opt/log
`

**Comment by comfuzio** [comment]
I tried to added quotes on the code, it is not there in the actual yml

**Comment by xavier-hernandez** [comment]
what browser are you using?

**Comment by comfuzio** [comment]
Chrome/Edge/Firefox. All update and problem is in all of them.
Something else I saw, this is a vm in proxmox, it was using CPU at max all the time.

**Comment by comfuzio** [comment]
Is there any logs I can share in order to solve this?

**Comment by xavier-hernandez** [comment]
sorry been busy with other things... let me figure out what I can do or what you can do to verify on your end that its working

**Comment by comfuzio** [comment]
do you need any logs from my end?

**Comment by xavier-hernandez** [comment]
So I'm not sure if this is something related to what your running across https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/issues/156 but this user has submitted a pull request. Let me review that code and if it looks good then I'll update the develop version of it so you can test it out.

**Comment by xavier-hernandez** [comment]
A new version has been deployed. Please pull the latest and let me know if that works.

**Comment by comfuzio** [comment]
> `version: '3.3' services: app: image: 'jc21/nginx-proxy-manager:latest' restart: unless-stopped ports: - '80:80' - '81:81' - '443:443' volumes: - ./data:/data - ./letsencrypt:/etc/letsencrypt
> 
> goaccess: image: 'xavierh/goaccess-for-nginxproxymanager:latest' container_name: goaccess restart: always ports: - '7880:7880' environment: - PUID=0 # Set to the User ID with read access to the log files (e.g., 0 for root) - PGID=0 # Set to the Group ID with read access to the log files (e.g., 0 for root) - TZ=Europe/Athens - SKIP_ARCHIVED_LOGS=False # optional - DEBUG=False # optional - BASIC_AUTH=False # optional - BASIC_AUTH_USERNAME=user # optional - BASIC_AUTH_PASSWORD=pass # optional - EXCLUDE_IPS=127.0.0.1 # optional - comma delimited - LOG_TYPE=NPM # optional - more information below volumes: - ./data/logs:/opt/log `

Dear Xavier, now it works!
Thank you Xavier!
What was the problem if I may ask?

**Comment by comfuzio** [comment]
And one last thing, I am hosting like 20 sites there, is there any way to get per domain stats instead of overall?

**Comment by xavier-hernandez** [comment]
> Dear Xavier, now it works! Thank you Xavier! What was the problem if I may ask?

Goaccess parses the files it tries to read and if it doesn't match the format you provided, then it kind of hangs or doesn't continue on with parsing the rest of the records. Another user has the same issue, and they found we could omit that check.

**Comment by xavier-hernandez** [comment]
> And one last thing, I am hosting like 20 sites there, is there any way to get per domain stats instead of overall?

No, there is no current way to do this at the moment. It's not a feature on the Goaccess side. From my end, the best I can do and it's currently part of this project if you look at the README is that you can filter a proxy host with -e INCLUDE_PROXY_HOSTS. But if you want to separate all your 20 websites, then you'd basically require 20 dockers running each pointing to a certain proxy host which is not a great option.
