### ISSUE TITLE
Native installation of goaccess for npm

### ISSUE THREAD

**Issue by second2falcon** [xavier-hernandez/goaccess-for-nginxproxymanager#158]
As I recently started trying to move all of my docker containers into LXC containers (in Proxmox), I am trying to install as many apps as possible natively (i.e. via binaries/executables) instead of via docker.

So far I have not found any way to install this (goaccess for NPM) natively on debian or alpine. Is this correct?

**Comment by second2falcon** [comment]
@xavier-hernandez should have been able to figure that out myself 🙄
Sorry for the stupid question, but what command is run within the container?
I have now been fidling around with goaccess for almost an hour with various commands from the internet and various combinations of the man pages, but haven't gotten the webserver to run a single time. (I know this is a more suited question for the goaccess side of things, but as the docker container seems to work flawlessly, I wanted to ask here first.) TIA

**Comment by xavier-hernandez** [comment]
It'd be something like this ./goaccess --num-tests=0 --no-global-config --config-file=${goan_config} &

your config would have to be setup for it to create the index page you can refer to this https://raw.githubusercontent.com/xavier-hernandez/goaccess-for-nginxproxymanager/main/resources/goaccess/goaccess.conf

**Comment by second2falcon** [comment]
I think this will point me in the right direction. Will check further with the people over at the GoAccess GH.

Will return once I have a solution and post it here.

**Comment by xavier-hernandez** [comment]
A shortcut would be to launch this docker image, then copy the configuration file within the container and you're basically done.

**Comment by second2falcon** [comment]
@xavier-hernandez 
Did that and with the help of some other guides it is now working.
The only thing I don't understand yet how it works, is the detection of new proxy hosts? Do you have a script which checks for that and then adds that new line or how did you do that?

**Comment by xavier-hernandez** [comment]
@second2falcon only a restart adds new proxy hosts. Its the same with the docker container.

**Comment by second2falcon** [comment]
@xavier-hernandez that is not the case for me. Might be something tho to do with the way NGINX/openresty interact with the dashboard as it is not one service anymore. Could also be because it's running on debian and not alpine. Will look into it further. 

Otherwise I should be able to use a regex in the goaccess.conf right?

**Comment by xavier-hernandez** [comment]
It all depends on how you have your configuration set up. I think your questions are more for https://github.com/allinurl/goaccess than this container.
