### ISSUE TITLE
Improve Traefik log format by supporting Virtual Hosts

### ISSUE THREAD

**Issue by Adito5393** [xavier-hernandez/goaccess-for-nginxproxymanager#168]
Regarding this line:
https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/blob/bd70f294dbd0fb2b000f13e83c3ee7626e158ecf/resources/scripts/logs/traefik.sh#L37

And following https://github.com/allinurl/goaccess/issues/966#issuecomment-494905087, could you replace it with:
```bash
echo "log-format ${LOG_FORMAT:-%h %^ %e [%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %^ \"%v\" %^ %Lms}" >> ${goan_config}
```

This change will introduce support for Virtual Hosts & fix the wrong loading time unit -> from `m` to `ms`

Example of an Traefik log:
```bash
1.1.1.1 - - [22/May/2019:17:41:50 +0000] "GET /api/v3/meta HTTP/1.1" 404 8849 "-" "-" 9 "some-rtr@docker" "http://172.1.0.11:3100" 1ms
```

**Comment by xavier-hernandez** [comment]
Added to v1.1.23 @Adito5393
