### ISSUE TITLE
goaccess new version

### ISSUE THREAD

**Issue by seb350** [xavier-hernandez/goaccess-for-nginxproxymanager#180]
Hello,

Thanks for the config of goaccess with npm. There's a new version of goaccess, can you update it please?

Also, wouldn't have been better to use the goaccess docker image as the base image? That way you wouldn't need to handle the goaccess update yourself.

Thanks again

**Comment by xavier-hernandez** [comment]
It's really just a zip file, and I have more control of it. There should be an update over the next few days.

**Comment by seb350** [comment]
Yeah I saw, I could update myself if that's what you mean but I'd have to build my own image based on a fork and maintain it :)

**Comment by xavier-hernandez** [comment]
updated new goaccess version and maxmind dbs

**Comment by seb350** [comment]
nice, thank you
