### ISSUE TITLE
Traefik format logs

### ISSUE THREAD

**Issue by SAOPP** [xavier-hernandez/goaccess-for-nginxproxymanager#19]
Hi!

Thanks, dope tool! One question, just interesting, is it possible to implement support for the log format of Traefik?

Thanks in advance!

**Comment by xavier-hernandez** [comment]
@SAOPP sorry for the delay in response. I currently don't run Traefik. That'd be probably another project/repo since this is specific to NPM but it should be possible. I've only run Traefik once in my life :P 

If your willing to assist I'm game for giving it a try.

**Comment by xavier-hernandez** [comment]
@SAOPP this weekend I'll set up Traefik and let you know when I have something feasible to test.

**Comment by SAOPP** [comment]
Dope! Wait for it. :)

**Comment by SAOPP** [comment]
Hi! Any news? :)

**Comment by xavier-hernandez** [comment]
@SAOPP 

I really put something quickly together https://github.com/xavier-hernandez/goaccess-for-traefik/tree/develop using this repo as a template.

Docker image available. I still need to research some things but just point it at your access.log file.

Open any tickets in that repo, please.

**Comment by SAOPP** [comment]
Wow homie, it's works!! :) Okay, I will switch to a new repo, thanks buddy!
