### ISSUE TITLE
Add docker option to skip loading archived logs

### ISSUE THREAD

**Issue by xavier-hernandez** [xavier-hernandez/goaccess-for-nginxproxymanager#2]

**Comment by parsoli** [comment]
+1 for value / ability to narrow date range as well...

**Comment by xavier-hernandez** [comment]
Added flag to skip archived logs. Available in the development branch.

https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/commit/fee6df1fb822b64d8ab78e3e32c9a565afd4a10f

**Comment by xavier-hernandez** [comment]
@parsoli narrowing date range is something that goaccess is currently working on for their UI and won't really be part of this docker image.

**Comment by xavier-hernandez** [comment]
Merged into main branch.

9cc805b8de8e74b86dd1c41530e9afdda9c598fb
