### ISSUE TITLE
Goaccess log errors

### ISSUE THREAD

**Issue by rtorchia** [xavier-hernandez/goaccess-for-nginxproxymanager#20]
Getting multiple errors from goaccess reading log files. Docker container then stops.

**FILE: /goaccess/access_archive.log**

- Token '009' doesn't match specifier '%s'
- Token 'SEARCH' doesn't match specifier '%m'
- Format Errors - Verify your log/date/time format

Running Nginx Proxy Manager v2.9.16 in docker container, on Ubuntu server 20.04

**Comment by rtorchia** [comment]
I deleted all my Nginx proxy manager logs and restarted the goaccess container, and now it is working.
Not the best fix, but it worked. There still may be something wrong with the log format for goaccess though

**Comment by xavier-hernandez** [comment]
Would you have a copy of the old logs, so that I can review?

**Comment by rtorchia** [comment]
Only after I deleted the backup copy of my log files did I realize that I probably should have kept them! 🤦
If the problem resurfaces I'll send you my log files to review.

**Comment by xavier-hernandez** [comment]
No problem. I'm wondering if there was some change in the NPM log format at some point in time. Another user had the same issue but it was only with one file once they deleted that one file it worked fine.

**Comment by rtorchia** [comment]
When I was getting the error, I had about 26 log files for each *_error..log and *_access.log. The errors were with multiple files, and the older log files it seemed were causing the issues. I'll keep an eye on it and report if it occurs again.

**Comment by xavier-hernandez** [comment]
@rtorchia please re-open if this issue comes back.
