### ISSUE TITLE
arm64 image version

### ISSUE THREAD

**Issue by NIghtHawkATL** [xavier-hernandez/goaccess-for-nginxproxymanager#23]
I enjoyed using your panel when I was using npm on a proxmox vm but decided to move it to a dedicated Pi and would like to continue to use goaccess on the Pi. Can you make an arm64 version?

**Comment by xavier-hernandez** [comment]
@NIghtHawkATL, for now, visit https://hub.docker.com/r/justsky/goaccess-for-nginxproxymanager for the ARM images.

**Comment by NIghtHawkATL** [comment]
Thank you! This works great!
