### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by rtorchia** [xavier-hernandez/goaccess-for-nginxproxymanager#24]
Latest image based on Alpine does not follow the set timezone in the TZ environment variable. The image based on ubuntu worked fine.

**Comment by xavier-hernandez** [comment]
@rtorchia are you using main or develop? Develop has been fixed. I've tested it on my remote machine. Thanks for opening the issue.

**Comment by rtorchia** [comment]
I used the main. I'll give it a try with the develop version

**Comment by rtorchia** [comment]
just pulled the develop version and the timezone working great!
Thank-you!!

**Comment by xavier-hernandez** [comment]
Pushed to main/latest
