### ISSUE TITLE
Live TX / RX

### ISSUE THREAD

**Issue by Albonycal** [xavier-hernandez/goaccess-for-nginxproxymanager#27]
Live bandwidth monitoring support would be nice
Thanks

**Comment by xavier-hernandez** [comment]
@Albonycal this project is mainly to allow easier access to GoAccess. That feature won't be a part of this project. Sorry. 

GoAccess does show you TX in the upper right-hand corner but pretty sure that's not what you're looking for.

![image](https://user-images.githubusercontent.com/6011223/159186184-4303ff1f-a98a-44c1-8dc0-1e4fc240f393.png)
