### ISSUE TITLE
A lot of CPU Usage and 15000 request every second in webUI

### ISSUE THREAD

**Issue by masterwishx** [xavier-hernandez/goaccess-for-nginxproxymanager#28]
Please check my post in Unraid forum https://forums.unraid.net/topic/120935-support-xavierh-goaccess-for-nginxproxymanager/?do=findComment&comment=1108337

**Comment by xavier-hernandez** [comment]
@masterwishx has this always been happening for you or just recently?

**Comment by masterwishx** [comment]
> @masterwishx has this always been happening for you or just recently?

i only yesterday founded it ,cant tell if it was always ,but when start docker its OK but with some time it has been add more and more request, i started docker now and will post here after some hours

**Comment by masterwishx** [comment]
its very strang but today its OK ,i cant see this problem ,so i think it was maybe only yesterday but i still check it and will check for some days also ...
![image](https://user-images.githubusercontent.com/28630321/159168456-cfa2087a-b009-4081-9eff-138c3d5279ea.png)
![image](https://user-images.githubusercontent.com/28630321/159168471-e070518b-8a88-4e00-8e16-fa704b06de11.png)

**Comment by xavier-hernandez** [comment]
If it was doing the 15k requests every second then I would assume that is why the CPU was high. Let me know if it continues to be an issue. Thanks.

**Comment by masterwishx** [comment]
OK

**Comment by xavier-hernandez** [comment]
@masterwishx still working? If so, I can close this ticket.

**Comment by masterwishx** [comment]
i have again this issue and but 9000 request every second for now , using docker with basic auth method , i was checked every day and in the morning was OK but now founded it again. how i can check from where thouse request maybe yo can tell ?
![image](https://user-images.githubusercontent.com/28630321/160016022-c6e8ba75-f540-479c-87e8-ad631baf8f36.png)
![image](https://user-images.githubusercontent.com/28630321/160016078-4bd562af-9524-451c-a99f-42a1cc2cf608.png)

**Comment by masterwishx** [comment]
please open issue

**Comment by masterwishx** [comment]
today after i turn off server for night i still have this isshue liek 9000 10000 request every second, and this eats 30% of CPU  :
maybe you can tell me what to check to find the problem?
![image](https://user-images.githubusercontent.com/28630321/160069073-69269389-1663-49fa-b745-5ba1651d4280.png)
