### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Silversurfer79** [xavier-hernandez/goaccess-for-nginxproxymanager#29]
I cannot get it to work on my Raspberry Pi (full updated). Latest version of docker and Portainer. I created a stack with the below and get this error: standard_init_linux.go:228: exec user process caused: exec format error

version: "3" 
services:
  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: GoAccess
    restart: always
    environment:
        - TZ=Europe/London
        - PUID=0
        - PGID=0
        - SKIP_ARCHIVED_LOGS=False #optional   
        - BASIC_AUTH=False #optional
        - BASIC_AUTH_USERNAME=user #docker admin account used
        - BASIC_AUTH_PASSWORD=pass #docker admin password used
    ports:
        - '7880:7880'
    volumes:
        - /home/pi/nginx/data/logs:/opt/log

**Comment by xavier-hernandez** [comment]
Currently, the ARM docker images are managed by @Just5KY 
 https://hub.docker.com/r/justsky/goaccess-for-nginxproxymanager

**Comment by Silversurfer79** [comment]
Thanks, will go there ;-)

**Comment by xavier-hernandez** [comment]
@Silversurfer79 can I close this?

**Comment by Silversurfer79** [comment]
Yes thanks
