### ISSUE TITLE
GoAccess dont get npm logs?

### ISSUE THREAD

**Issue by zeus1999** [xavier-hernandez/goaccess-for-nginxproxymanager#30]
I run NPM in an docker container with the following map                /root/npm/data      ->        /data

when i add a new container:
```

docker create -it \
--name=Goaccess \
--restart=always \
-p 7880:7880 \
-v /root/npm/data/logs:/opt/log \
-e SKIP_ARCHIVED_LOGS=False \
xavierh/goaccess-for-nginxproxymanager:latest


```

I can open the page but it stays by zero.

ls -la  (/root/npm/data/logs)
```


total 1087060
drwxr-xr-x 2 root root      4096 Mar 21 18:38  .
drwxr-xr-x 8 root root      4096 May  2  2021  ..
-rw-r--r-- 1 root root  68288072 Mar 21 18:48  default.log
-rw-r--r-- 1 root root  63622832 Mar 21 19:10  default_host.log
-rw-r--r-- 1 root root   5975518 Mar 21 18:17  error.log
-rw-r--r-- 1 root root     36717 Mar  6 12:27  letsencrypt-requests.log
-rw-r--r-- 1 root root        42 Mar 21 18:38 'og-format=%h %^[%d:%t %^] %v "%r" "%s" %b "%R" "%u" %^'
-rw-r--r-- 1 root root  34559380 Mar 21 19:10  proxy_host-1.log
-rw-r--r-- 1 root root    111554 Oct 12 03:23  proxy_host-12.log
-rw-r--r-- 1 root root     63496 Jul  4  2021  proxy_host-16.log
-rw-r--r-- 1 root root  14267140 Oct 12 03:28  proxy_host-17.log
-rw-r--r-- 1 root root    161921 Jul 18  2021  proxy_host-18.log
-rw-r--r-- 1 root root       598 Aug 20  2021  proxy_host-19.log
-rw-r--r-- 1 root root    609702 Dec 31 05:01  proxy_host-2.log
-rw-r--r-- 1 root root     78830 Nov  4 12:46  proxy_host-20.log
-rw-r--r-- 1 root root         0 Nov  6 22:05  proxy_host-21.log
-rw-r--r-- 1 root root         0 Nov  6 22:05  proxy_host-22.log
-rw-r--r-- 1 root root    278802 Jan  1 03:18  proxy_host-23.log
-rw-r--r-- 1 root root  24156909 Jan  1 22:13  proxy_host-24.log
-rw-r--r-- 1 root root   1073652 Mar 21 12:27  proxy_host-25.log
-rw-r--r-- 1 root root     24098 Nov 12 17:34  proxy_host-26.log
-rw-r--r-- 1 root root    105417 Nov 29 12:05  proxy_host-27.log
-rw-r--r-- 1 root root     13086 Nov 12 17:34  proxy_host-28.log
-rw-r--r-- 1 root root     15239 Nov 12 20:54  proxy_host-29.log
-rw-r--r-- 1 root root  58394594 Mar 21 19:12  proxy_host-3.log
-rw-r--r-- 1 root root     15617 Nov 12 20:54  proxy_host-30.log
-rw-r--r-- 1 root root      5904 Nov 12 20:54  proxy_host-31.log
-rw-r--r-- 1 root root      5896 Nov 12 23:01  proxy_host-32.log
-rw-r--r-- 1 root root      9349 Nov 13 01:20  proxy_host-33.log
-rw-r--r-- 1 root root    309088 Dec 29 16:43  proxy_host-34.log
-rw-r--r-- 1 root root      4788 Nov 25 14:22  proxy_host-35.log
-rw-r--r-- 1 root root      4117 Nov 13 01:21  proxy_host-36.log
-rw-r--r-- 1 root root         0 Nov 13 01:22  proxy_host-37.log
-rw-r--r-- 1 root root         0 Nov 13 01:22  proxy_host-38.log
-rw-r--r-- 1 root root      4110 Nov 13 01:22  proxy_host-39.log
-rw-r--r-- 1 root root         0 Nov 13 22:46  proxy_host-40.log
-rw-r--r-- 1 root root     54045 Dec 31 12:51  proxy_host-41.log
-rw-r--r-- 1 root root     25215 Dec 28 10:55  proxy_host-42.log
-rw-r--r-- 1 root root         0 Nov 25 07:56  proxy_host-43.log
-rw-r--r-- 1 root root         0 Nov 25 07:57  proxy_host-44.log
-rw-r--r-- 1 root root      2525 Nov 28 01:41  proxy_host-45.log
-rw-r--r-- 1 root root     12328 Nov 28 01:40  proxy_host-46.log
-rw-r--r-- 1 root root      8839 Nov 28 01:39  proxy_host-47.log
-rw-r--r-- 1 root root    139091 Mar 20 22:45  proxy_host-48.log
-rw-r--r-- 1 root root    323933 Mar 21 13:40  proxy_host-49.log
-rw-r--r-- 1 root root  63630789 Mar 21 19:12  proxy_host-5.log
-rw-r--r-- 1 root root   1013726 Jan 31 23:11  proxy_host-50.log
-rw-r--r-- 1 root root 527660441 Mar 21 19:12  proxy_host-51.log
-rw-r--r-- 1 root root     45142 Jan 10 13:04  proxy_host-52.log
-rw-r--r-- 1 root root     47567 Mar 19 05:21  proxy_host-53.log
-rw-r--r-- 1 root root     70911 Mar 21 12:27  proxy_host-54.log
-rw-r--r-- 1 root root   2734245 Mar 21 12:27  proxy_host-55.log
-rw-r--r-- 1 root root    351558 Mar 20 14:22  proxy_host-56.log
-rw-r--r-- 1 root root     27049 Mar 16 22:19  proxy_host-57.log
-rw-r--r-- 1 root root    129794 Mar 21 12:28  proxy_host-58.log
-rw-r--r-- 1 root root     31082 Mar 21 12:28  proxy_host-59.log
-rw-r--r-- 1 root root  56955513 Mar 21 19:12  proxy_host-6.log
-rw-r--r-- 1 root root    877462 Mar 18 13:58  proxy_host-60.log
-rw-r--r-- 1 root root 102583938 Mar 21 19:12  proxy_host-7.log
-rw-r--r-- 1 root root  36479510 Mar 21 19:10  redirection_host-1.log
-rw-r--r-- 1 root root  47254508 Mar 21 19:12  redirection_host-3.log
-rw-r--r-- 1 root root    212723 Nov 11 03:01  redirection_host-4.log
```

**Comment by xavier-hernandez** [comment]
I recommend you do "docker container logs Goaccess" it should tell you if the docker container can read your logs files. It could be a permission issue..

**Comment by zeus1999** [comment]
> 

it says


```
No archived logs found...
Checking active logs...
 [SETTING UP STORAGE /goaccess/access.log] {0} @ {0/s}
WebSocket server ready to accept new client connections
```


thats strange. there is an large default.log file

**Comment by xavier-hernandez** [comment]
It doesn't currently process the default.log. It's on the list to do since it's a different log format. 

It should be listing all the files it found. Something like below. Are your logs stored at "/npm/data/logs" or "/root/npm/data/logs" ? I noticed that in your first comment. Please verify the location of the logs.

Loading (94) archived logs...
Checking active logs...
Filename: /opt/log/proxy-host-6_access.log | Read = yes
Filename: /opt/log/proxy-host-24_access.log | Read = yes
Filename: /opt/log/proxy-host-9_access.log | Read = yes
Filename: /opt/log/proxy-host-10_access.log | Read = yes
Filename: /opt/log/proxy-host-14_access.log | Read = yes
Filename: /opt/log/proxy-host-17_access.log | Read = yes
Filename: /opt/log/proxy-host-21_access.log | Read = yes
Filename: /opt/log/proxy-host-18_access.log | Read = yes
Filename: /opt/log/proxy-host-26_access.log | Read = yes
Filename: /opt/log/proxy-host-16_access.log | Read = yes
Filename: /opt/log/proxy-host-25_access.log | Read = yes
Filename: /opt/log/proxy-host-15_access.log | Read = yes
Filename: /opt/log/proxy-host-19_access.log | Read = yes
Filename: /opt/log/proxy-host-4_access.log | Read = yes
Filename: /opt/log/proxy-host-5_access.log | Read = yes
Filename: /opt/log/proxy-host-1_access.log | Read = yes
Filename: /opt/log/proxy-host-12_access.log | Read = yes
Filename: /opt/log/proxy-host-11_access.log | Read = yes
Filename: /opt/log/proxy-host-27_access.log | Read = yes
Filename: /opt/log/proxy-host-20_access.log | Read = yes
Filename: /opt/log/proxy-host-23_access.log | Read = yes
Filename: /opt/log/proxy-host-2_access.log | Read = yes
Filename: /opt/log/proxy-host-8_access.log | Read = yes
Filename: /opt/log/proxy-host-7_access.log | Read = yes
Filename: /opt/log/proxy-host-13_access.log | Read = yes
Filename: /opt/log/proxy-host-22_access.log | Read = yes
Filename: /opt/log/proxy-host-3_access.log | Read = yes
Loading proxy-host logs...
 [PARSING /opt/log/proxy-host-26_access.log] {39} @ {0/s}0/s}
WebSocket server ready to accept new client connections

**Comment by zeus1999** [comment]
> It doesn't currently process the default.log. It's on the list to do since it's a different log format.
> 
> It should be listing all the files it found. Something like below. Are your logs stored at "/npm/data/logs" or "/root/npm/data/logs" ? I noticed that in your first comment. Please verify the location of the logs.
> 
> Loading (94) archived logs... Checking active logs... Filename: /opt/log/proxy-host-6_access.log | Read = yes Filename: /opt/log/proxy-host-24_access.log | Read = yes Filename: /opt/log/proxy-host-9_access.log | Read = yes Filename: /opt/log/proxy-host-10_access.log | Read = yes Filename: /opt/log/proxy-host-14_access.log | Read = yes Filename: /opt/log/proxy-host-17_access.log | Read = yes Filename: /opt/log/proxy-host-21_access.log | Read = yes Filename: /opt/log/proxy-host-18_access.log | Read = yes Filename: /opt/log/proxy-host-26_access.log | Read = yes Filename: /opt/log/proxy-host-16_access.log | Read = yes Filename: /opt/log/proxy-host-25_access.log | Read = yes Filename: /opt/log/proxy-host-15_access.log | Read = yes Filename: /opt/log/proxy-host-19_access.log | Read = yes Filename: /opt/log/proxy-host-4_access.log | Read = yes Filename: /opt/log/proxy-host-5_access.log | Read = yes Filename: /opt/log/proxy-host-1_access.log | Read = yes Filename: /opt/log/proxy-host-12_access.log | Read = yes Filename: /opt/log/proxy-host-11_access.log | Read = yes Filename: /opt/log/proxy-host-27_access.log | Read = yes Filename: /opt/log/proxy-host-20_access.log | Read = yes Filename: /opt/log/proxy-host-23_access.log | Read = yes Filename: /opt/log/proxy-host-2_access.log | Read = yes Filename: /opt/log/proxy-host-8_access.log | Read = yes Filename: /opt/log/proxy-host-7_access.log | Read = yes Filename: /opt/log/proxy-host-13_access.log | Read = yes Filename: /opt/log/proxy-host-22_access.log | Read = yes Filename: /opt/log/proxy-host-3_access.log | Read = yes Loading proxy-host logs... [PARSING /opt/log/proxy-host-26_access.log] {39} @ {0/s}0/s} WebSocket server ready to accept new client connections

verified. pwd is /root/npm/data/logs

**Comment by zeus1999** [comment]
> It's not an ARM device I assume? What's OS?

Its an LXC (Ubuntu 21.04) on an Proxmox server

**Comment by rtorchia** [comment]
@zeus1999 
I could be reading to much into your replies, but check your path to your log files.
You replied that your logs are at _/npm/data/logs_, but your script has _/root/npm/data/logs_
If so, then you should have:

> -v /npm/data/logs:/opt/log

**Comment by zeus1999** [comment]
i triple checked it now. the logs are here:     /root/npm/data/logs

**Comment by rtorchia** [comment]
That good to know.
I had problems with goaccess not readying my log files until I deleted everything in the logs directory and started fresh.
Looking at your directory, there is a strange file
> 'og-format=%h %^[%d:%t %^] %v "%r" "%s" %b "%R" "%u" %^'

Wonder if you are having something similar to what I experienced

**Comment by zeus1999** [comment]
> That good to know. I had problems with goaccess not readying my log files until I deleted everything in the logs directory and started fresh. Looking at your directory, there is a strange file
> 
> > 'og-format=%h %^[%d:%t %^] %v "%r" "%s" %b "%R" "%u" %^'
> 
> Wonder if you are having something similar to what I experienced

Very Strange, i removed all log files restartet the system, created the container, and same problem....

**Comment by xavier-hernandez** [comment]
@zeus1999 I see the issue. I didn't realize it before but your filenames are different. The app reads "proxy-host-*_access.log" files. Your file is called proxy_host-37.log.

What version of NPM are you running?

**Comment by zeus1999** [comment]
> @zeus1999 I see the issue. I didn't realize it before but your filenames are different. The app reads "proxy-host-*_access.log" files. Your file is called proxy_host-37.log.
> 
> For example... proxy-host-8_access.log proxy-host-8_error.log
> 
> What version of NPM are you running?

according to the webui> v2.8.1

**Comment by xavier-hernandez** [comment]
The latest is 2.9.16. Before we have you updating NPM or anything like that. Would it be possible to send me a sample log file? I'd like to check the log file and see if it matches the current log files structure.

**Comment by zeus1999** [comment]
> The latest is 2.9.16. Before we have you updating NPM or anything like that. Would it be possible to send me a sample log file? I'd like to check the log file and see if it matches the current log file structure.

Sure, i would delete the link, after you have downloaded it.

https://pastebin.com/V93vpZ6Z

**Comment by xavier-hernandez** [comment]
Got it, feel free to delete.

**Comment by xavier-hernandez** [comment]
@zeus1999 I think you sent me a redirection log is that correct? I need a proxy_host-*.log. It just needs to be a few lines as well.

**Comment by zeus1999** [comment]
> @zeus1999 I think you sent me a redirection log is that correct? I need a proxy_host-*.log. It just needs to be a few lines as well.

Sorry! My fault. Here you go:  https://pastebin.com/KseZSSiE

**Comment by xavier-hernandez** [comment]
Got it!

**Comment by xavier-hernandez** [comment]
@zeus1999 

I've made a mod to the script that looks for the proxy files. 

"proxy-host-*.log" except anything containing "*_error.log" which will exclude the error logs for now.

Can you pull down the dev version and see if it works for you? xavierh/goaccess-for-nginxproxymanager:develop

**Comment by xavier-hernandez** [comment]
I still can't find documentation of when this changed. I've searched the NPM repo. I do see examples of log files names in comments from 2019 that differ from comments made in 2021/2022. 

¯\_(ツ)_/¯

**Comment by zeus1999** [comment]
> @zeus1999
> 
> I've made a mod to the script that looks for the proxy files.
> 
> "proxy-host-_.log" except anything containing "__error.log" which will exclude the error logs for now.
> 
> Can you pull down the dev version and see if it works for you? xavierh/goaccess-for-nginxproxymanager:develop

Thanks!

But it doesnt work either. Same problem, same output.

I created the container

```
docker create -it \
--name=Goaccess \
--restart=always \
-p 7880:7880 \
-v /root/npm/data/logs:/opt/log \
-e SKIP_ARCHIVED_LOGS=False \
xavierh/goaccess-for-nginxproxymanager:develop
```

**Comment by zeus1999** [comment]
> can you send over the logs again? docker container logs Goaccess
> 
> then can you go into the docker container itself?
> 
> * docker exec -it Goaccess /bin/bash
> * navigate to /opt/log
> * do a ls command and send over the output
> * then "exit"

docker container logs Goaccess

```
No archived logs found...
Checking active logs...
 [SETTING UP STORAGE /goaccess/access.log] {0} @ {0/s}
WebSocket server ready to accept new client connections
```





ls
```

default.log                                             proxy_host-23.log                                       proxy_host-37.log                                       proxy_host-51.log
default_host.log                                        proxy_host-24.log                                       proxy_host-38.log                                       proxy_host-52.log
error.log                                               proxy_host-25.log                                       proxy_host-39.log                                       proxy_host-53.log
letsencrypt-requests.log                                proxy_host-26.log                                       proxy_host-40.log                                       proxy_host-54.log
og-format=%h %^[%d:%t %^] %v "%r" "%s" %b "%R" "%u" %^  proxy_host-27.log                                       proxy_host-41.log                                       proxy_host-55.log
proxy_host-1.log                                        proxy_host-28.log                                       proxy_host-42.log                                       proxy_host-56.log
proxy_host-12.log                                       proxy_host-29.log                                       proxy_host-43.log                                       proxy_host-57.log
proxy_host-16.log                                       proxy_host-3.log                                        proxy_host-44.log                                       proxy_host-58.log
proxy_host-17.log                                       proxy_host-30.log                                       proxy_host-45.log                                       proxy_host-59.log
proxy_host-18.log                                       proxy_host-31.log                                       proxy_host-46.log                                       proxy_host-6.log
proxy_host-19.log                                       proxy_host-32.log                                       proxy_host-47.log                                       proxy_host-60.log
proxy_host-2.log                                        proxy_host-33.log                                       proxy_host-48.log                                       proxy_host-7.log
proxy_host-20.log                                       proxy_host-34.log                                       proxy_host-49.log                                       redirection_host-1.log
proxy_host-21.log                                       proxy_host-35.log                                       proxy_host-5.log                                        redirection_host-3.log
proxy_host-22.log                                       proxy_host-36.log                                       proxy_host-50.log                                       redirection_host-4.log
```

**Comment by xavier-hernandez** [comment]
I can confirm it works on my end using a file you sent me yesterday with the filename you are using.

If you used the develop tag in the past maybe do "docker pull xavierh/goaccess-for-nginxproxymanager:develop" to get the latest.

docker run --name=Goaccess --restart=always -p 7880:7880 -v /opt/sample-logs-develop:/opt/log -e SKIP_ARCHIVED_LOGS=False xavierh/goaccess-for-nginxproxymanager:develop

/opt/sample-logs-develop contains one log file called proxy-host-2.log

No archived logs found...
Checking active logs...
Filename: /opt/log/proxy-host-2.log | Read = yes
Loading proxy-host logs...
 [SETTING UP STORAGE /opt/log/proxy-host-2.log] {0} @ {0/s}
WebSocket server ready to accept new client connections

![image](https://user-images.githubusercontent.com/6011223/159557423-8669a032-0825-4343-80f6-3fe43be56946.png)

**Comment by xavier-hernandez** [comment]
Other than a couple of file names I don't believe there is any personal information in the screenshot. Let me know if you want me to remove it.

Also, can you try going back in the container and do a "cat proxy_host-1.log" and check if any data is displayed. It should detect file permissions but maybe its not. Just want to verify that and cover all the basics.

Thanks.

**Comment by buzzke** [comment]
Seems like a mismatch between the Arm and Amd version.
Had the same issue on the Arm docker image (jc21/nginx-proxy-manager:latest)
As a test i deployed the same image on a Amd machine.  And the logs are indeed in different format.

`total 456
-rwxrwxrwx+ 1 root root   3304 Mar 25 11:26 fallback_access.log
-rwxrwxrwx+ 1 root root    713 Mar 25 11:04 fallback_error.log
-rwxrwxrwx+ 1 root root   5592 Mar 25 11:23 letsencrypt-requests_access.log
-rwxrwxrwx+ 1 root root      0 Mar 25 10:41 letsencrypt-requests_error.log
-rwxrwxrwx+ 1 root root 143055 Mar 25 10:57 proxy-host-1_access.log
-rwxrwxrwx+ 1 root root   4289 Mar 25 10:45 proxy-host-1_error.log
-rwxrwxrwx+ 1 root root  80728 Mar 25 11:12 proxy-host-2_access.log
-rwxrwxrwx+ 1 root root      0 Mar 25 10:44 proxy-host-2_error.log
-rwxrwxrwx+ 1 root root  98921 Mar 25 11:29 proxy-host-3_access.log
-rwxrwxrwx+ 1 root root   1427 Mar 25 11:28 proxy-host-3_error.log
-rwxrwxrwx+ 1 root root  92033 Mar 25 11:24 proxy-host-4_access.log
-rwxrwxrwx+ 1 root root   2716 Mar 25 10:50 proxy-host-4_error.log
-rwxrwxrwx+ 1 root root   5560 Mar 25 11:31 proxy-host-5_access.log
-rwxrwxrwx+ 1 root root    215 Mar 25 11:24 proxy-host-5_error.log
`

**Comment by zeus1999** [comment]
> 

Yeah I see, i could get this to run. Always stays by No archived logs found

**Comment by xavier-hernandez** [comment]
@zeus1999 it started working for you overall, just no archives found?

Archived/old data has an extension of .gz at least in my case. Do you see anything like that on your version?

**Comment by zeus1999** [comment]
> @zeus1999 it started working for you overall, just no archives found?
> 
> Archived/old data has an extension of .gz at least in my case. Do you see anything like that on your NPM version?

No not working. There is any compressed file. Only proxy_host-x.log and some other log files. See here: https://pastebin.com/ugLzuMxn

**Comment by xavier-hernandez** [comment]
@zeus1999 since there are no .gz files then it'll always tell you it didn't find any archive files.

Have you tried adding the following, looks your log files are created another root?

    environment:
        - PUID=0
        - PGID=0

**Comment by xavier-hernandez** [comment]
@zeus1999 also please pull the latest from the develop image. This is what your docker-compose should look like.

goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:develop
    container_name: goaccess
    restart: always
    volumes:
        - /root/npm/data/logs:/opt/log
    ports:
        - '7880:7880'
    environment:
        - PUID=0
        - PGID=0
        - TZ=America/New_York        
        - SKIP_ARCHIVED_LOGS=False #optional
        - BASIC_AUTH=False #optional
        - BASIC_AUTH_USERNAME=user #optional
        - BASIC_AUTH_PASSWORD=pass #optional

**Comment by zeus1999** [comment]
> @zeus1999 also please pull the latest from the develop image. This is what your docker-compose should look like. I've tried plugging everything as part of your post. You'll need to set the right timezone.
> 
> ```yaml
> goaccess:
>     image: xavierh/goaccess-for-nginxproxymanager:develop
>     container_name: goaccess
>     restart: always
>     volumes:
>         - /root/npm/data/logs:/opt/log
>     ports:
>         - '7880:7880'
>     environment:
>         - PUID=0
>         - PGID=0
>         - TZ=America/New_York        
>         - SKIP_ARCHIVED_LOGS=False #optional
>         - BASIC_AUTH=False #optional
>         - BASIC_AUTH_USERNAME=user #optional
>         - BASIC_AUTH_PASSWORD=pass #optional      
> ```

i created the docker compose exactly from your paste:

this output:

```
root@Service-nginx:~/test# docker-compose up
Creating goaccess ... done
Attaching to goaccess
goaccess    | No archived logs found...
goaccess    | Checking active logs...
goaccess    |  [SETTING UP STORAGE /goaccess/access.log] {0} @ {0/s}
WebSocket server ready to accept new client connections

```

i entered the shell from the docker container and can see the logs and also read them. 

but same result? what am i doing wrong?

**Comment by xavier-hernandez** [comment]
@zeus1999 

That looks like an old image, I added a version number recently.

run "docker pull image xavierh/goaccess-for-nginxproxymanager:develop" then run "docker-compose up" again

**Comment by zeus1999** [comment]
> 

true

new log
```

Recreating goaccess ... done
Attaching to goaccess
goaccess    | 
goaccess    | GOAN v1.0.3
goaccess    | 
goaccess    | No archived logs found at /opt/log...
goaccess    | Checking active logs...
goaccess    | 
goaccess    | Processing (0) total log(s)...
goaccess    | 
goaccess    | 
WebSocket server ready to accept new client connections
```

**Comment by xavier-hernandez** [comment]
A new version has been pushed out. Try that one. 

docker pull xavierh/goaccess-for-nginxproxymanager:develop
