### ISSUE TITLE
Feature? Read into rotated logs

### ISSUE THREAD

**Issue by Goro2030** [xavier-hernandez/goaccess-for-nginxproxymanager#33]
Shouldn't be nice if GoAccess would process the compressed rotated logs from NGINX?

I have this:

-rw-r--r-- 1 root root    17247 Mar 24 08:54 proxy-host-8_access.log
-rw-r--r-- 1 root root     2153 Mar 19 23:28 proxy-host-8_access.log.1.gz
-rw-r--r-- 1 root root     2793 Mar 14 05:56 proxy-host-8_access.log.2.gz
-rw-r--r-- 1 root root     3515 Mar  6 01:35 proxy-host-8_access.log.3.gz
-rw-r--r-- 1 root root     2413 Feb 28 05:06 proxy-host-8_access.log.4.gz
-rw-r--r-- 1 root root        0 Nov 20 08:34 proxy-host-8_error.log
-rw-r--r-- 1 root root      308 Nov 12 15:21 proxy-host-8_error.log.1.gz

And it's only processing the .log files.

**Comment by xavier-hernandez** [comment]
@Goro2030 what version are you using?

It should be processing the archived one. Do a "docker container logs container-name" and provide the output.

**Comment by xavier-hernandez** [comment]
I'm currently running the development version but you should see something similar to this...

```code
GOAN v1.0.3

Loading (94) archived logs from /opt/log...
Checking active logs...
         Filename: /opt/log/proxy-host-6_access.log | Read = yes
         Filename: /opt/log/proxy-host-24_access.log | Read = yes
         Filename: /opt/log/proxy-host-9_access.log | Read = yes
         Filename: /opt/log/proxy-host-10_access.log | Read = yes
         Filename: /opt/log/proxy-host-14_access.log | Read = yes
         Filename: /opt/log/proxy-host-17_access.log | Read = yes
         Filename: /opt/log/proxy-host-28_access.log | Read = yes
         Filename: /opt/log/proxy-host-21_access.log | Read = yes
         Filename: /opt/log/proxy-host-18_access.log | Read = yes
         Filename: /opt/log/proxy-host-26_access.log | Read = yes
         Filename: /opt/log/proxy-host-16_access.log | Read = yes
         Filename: /opt/log/proxy-host-25_access.log | Read = yes
         Filename: /opt/log/proxy-host-15_access.log | Read = yes
         Filename: /opt/log/proxy-host-19_access.log | Read = yes
         Filename: /opt/log/proxy-host-4_access.log | Read = yes
         Filename: /opt/log/proxy-host-5_access.log | Read = yes
         Filename: /opt/log/proxy-host-1_access.log | Read = yes
         Filename: /opt/log/proxy-host-12_access.log | Read = yes
         Filename: /opt/log/proxy-host-11_access.log | Read = yes
         Filename: /opt/log/proxy-host-27_access.log | Read = yes
         Filename: /opt/log/proxy-host-20_access.log | Read = yes
         Filename: /opt/log/proxy-host-23_access.log | Read = yes
         Filename: /opt/log/proxy-host-2_access.log | Read = yes
         Filename: /opt/log/proxy-host-8_access.log | Read = yes
         Filename: /opt/log/proxy-host-7_access.log | Read = yes
         Filename: /opt/log/proxy-host-13_access.log | Read = yes
         Filename: /opt/log/proxy-host-22_access.log | Read = yes
         Filename: /opt/log/proxy-host-3_access.log | Read = yes
Found (28) proxy logs....

Processing (122) total log(s)...

 [RENDERING /opt/log/proxy-host-3_access.log] {22} @ {0/s}/s}}
WebSocket server ready to accept new client connections
```

**Comment by Goro2030** [comment]
I see something like that, exactly ... but as it didn't say anything about .gz files, my assumption is that it didn't ingest .gz files...

Loading (29) archived logs...
Checking active logs...
Filename: /opt/log/proxy-host-6_access.log | Read = yes
Filename: /opt/log/proxy-host-3_access.log | Read = yes
Filename: /opt/log/proxy-host-9_access.log | Read = yes
Filename: /opt/log/proxy-host-2_access.log | Read = yes
Filename: /opt/log/proxy-host-7_access.log | Read = yes
Filename: /opt/log/proxy-host-1_access.log | Read = yes
Filename: /opt/log/proxy-host-8_access.log | Read = yes
Filename: /opt/log/proxy-host-5_access.log | Read = yes
Filename: /opt/log/proxy-host-4_access.log | Read = yes
Loading proxy-host logs...

I have GZ files from last october, and in the dashboard I see activity since February of this year

**Comment by xavier-hernandez** [comment]
Loading (29) archived logs... means it's looking through the .gz files.

Run the following command in your logs directory and post the output. This should return the last 10 proxy-host access gz files.

ls -lt proxy-host-*_access* | tail -10

**Comment by Goro2030** [comment]
Yeah... it looks like the old logs are too tiny... i looked into them and they have just 20-30 log entries only. Case closed!

ls -lt proxy-host- ? _access * | tail -10
-rw-r--r-- 1 root root   9708 Feb 20 07:00 proxy-host-9_access.log.4.gz
-rw-r--r-- 1 root root   9211 Feb 20 07:00 proxy-host-7_access.log.4.gz
-rw-r--r-- 1 root root  10061 Feb 20 06:59 proxy-host-6_access.log.4.gz
-rw-r--r-- 1 root root  10067 Feb 20 06:59 proxy-host-4_access.log.4.gz
-rw-r--r-- 1 root root  11110 Feb 20 06:59 proxy-host-8_access.log.4.gz
-rw-r--r-- 1 root root    525 Nov  8 01:41 proxy-host-5_access.log.1.gz
-rw-r--r-- 1 root root    431 Nov  4 07:28 proxy-host-5_access.log.2.gz
-rw-r--r-- 1 root root    147 Oct 26 16:10 proxy-host-5_access.log.3.gz
-rw-r--r-- 1 root root    338 Oct 21 11:36 proxy-host-5_access.log.4.gz
-rw-r--r-- 1 root root    408 Sep  7  2021 proxy-host-2_access.log.1.gz

**Comment by Goro2030** [comment]
Thanks for the quick support @xavier-hernandez !! You rock! Great product, keep it going!

**Comment by xavier-hernandez** [comment]
No problem ;)
