### ISSUE TITLE
Cumulative data

### ISSUE THREAD

**Issue by xavier-hernandez** [xavier-hernandez/goaccess-for-nginxproxymanager#37]
Prior to deploying the latest, v1.04, I tested against my production server and the number of hits went down drastically. I had over 1,000,000 million requests compared now to 600,000. 

I tested the docker image and that is not the issue. I tested the logs with the "latest" older version and the stats were the same. I also tested via the goaccess cli and the results were the same. 

I'm not sure if the discrepancy is caused by NPM or GoAccess. I'm thinking NPM. Maybe NPM is not keeping all its data? Should I look into disk persistence?

**Comment by rtorchia** [comment]
yup, everything has been looking good.  I even updated today to npm 2.9.17 and checked on everything and it looks fine. All running under Docker on Ubuntu server 20.04

**Comment by xavier-hernandez** [comment]
closing for now... maybe I deleted some proxies
