### ISSUE TITLE
Need support for another filename format of NPM log files

### ISSUE THREAD

**Issue by fuuman** [xavier-hernandez/goaccess-for-nginxproxymanager#44]
My Nginx Proxy Manager saves log files as `proxy_host-2.log` with an underscore between `proxy` and `host`. Currently that's not supported.

**Comment by fuuman** [comment]
It's working!

**Comment by xavier-hernandez** [comment]
@fuuman do you have archive logs ending in .gz ? If so, what is the filename for those.
