### ISSUE TITLE
Date range selector

### ISSUE THREAD

**Issue by adidgit** [xavier-hernandez/goaccess-for-nginxproxymanager#45]
Hi,

Would be great if there was a date range selector where you can select specific dates so to be able to review specific data.

Thanks

**Comment by xavier-hernandez** [comment]
@adidgit in the UI or in the logs imported? If its the UI, then that would be something for goaccess, https://github.com/allinurl/goaccess

**Comment by adidgit** [comment]
Hi, In the UI. Yes, you are right. Goaccess would be the right place.
BTW...Thanks for the excellent application!
