### ISSUE TITLE
Feature Request - capability to access the --exclude-ip option in GoAccess.

### ISSUE THREAD

**Issue by beastarman74** [xavier-hernandez/goaccess-for-nginxproxymanager#46]
This would allow the exclusion of specific IP's/IP ranges from the GoAccess charts. 

This will help with excluding monitoring tools entries in the log files e.g. from uptime-kuma.

**Comment by xavier-hernandez** [comment]
I'll go ahead and look into this.

**Comment by Reupireup** [comment]
I can generate manually with excluding my router ip with the command : 
`/goaccess/goaccess -f /goaccess-config/access_archive.log --log-format='[%d:%t %^] %^ %^ %s - %m %^ %v "%U" [Client %h] [Length %b] [Gzip %^] [Sent-to %^] "%u" "%R"' --date-format='%d/%b/%Y' --date-spec=hr --time-format='%H:%M:%S' -a -e <MYIP> -o /opt/log/result.html`
alternatively /goaccess-config/goaccess.conf contains (line ~390) a bunch of commented exclude-ip configs.

hope it will help
