### ISSUE TITLE
allow mounting of goaccess.conf

### ISSUE THREAD

**Issue by xavier-hernandez** [xavier-hernandez/goaccess-for-nginxproxymanager#5]
The current code does not allow the user to update the goaccess.conf. It would be nice to give the user a choice to load their own for customizations such as panels, static files, etc.

**Comment by arsaboo** [comment]
Alternatively, expose some options such as `exlcude-ip` using environmental variables

**Comment by xavier-hernandez** [comment]
@arsaboo exclude IP has now been exposed, please checkout the latest version

**Comment by xavier-hernandez** [comment]
Closing this. I don't think allowing the mounting of the configuration is going to happen due to the need in supporting and fixing bugs. Allowing customer configurations will just add another layer to get through to support the container/image.
