### ISSUE TITLE
Request: please enable redirection-host-*_access.log 

### ISSUE THREAD

**Issue by niceborn** [xavier-hernandez/goaccess-for-nginxproxymanager#50]
Hi,

thanks for the good work. I have a wish to you.

Right now it seems that only Proxy logs are processed. I would like also to have the redirection logs redirection-host-*_access.log to be imported.

BR
Michael

**Comment by xavier-hernandez** [comment]
I'll go ahead and look into this. I started a while back. I think I'd need to run 2 different goaccess processes for this.

**Comment by xavier-hernandez** [comment]
@niceborn I'll be working on this soon. I had to do some refactoring of the code to handle this.

**Comment by xavier-hernandez** [comment]
@niceborn this should be available in the next version. I've figured out the coding just need to implement it.

**Comment by xavier-hernandez** [comment]
@niceborn the develop branch and image have been updated to support the redirection logs. If you'd like to test it out feel free.

docker pull xavierh/goaccess-for-nginxproxymanager:develop

Please review the readme file. You need to pass the environment flag LOG_TYPE of NPM+R for a second instance to be created. The first instance of goaccess within the container will read the npm proxy logs and the second install will read the npm redirection logs.

**Comment by niceborn** [comment]
@xavier-hernandez works like a charm. Also the readme is understandable. Thanks for the solution.

**Comment by xavier-hernandez** [comment]
@niceborn that's great. Thanks for testing!

**Comment by xavier-hernandez** [comment]
This has now been deployed to the main branch and latest tag.
