### ISSUE TITLE
error after update...

### ISSUE THREAD

**Issue by hs6666** [xavier-hernandez/goaccess-for-nginxproxymanager#61]
Hi,

Since previous update, will not start up, get following error in log file....

/goan/start.sh: /goan/funcs/environment.sh: line 16: syntax error: unexpected redirection

Any ideas please?

Thanks

**Comment by xavier-hernandez** [comment]
@hs6666 are you running the last build, v1.0.9? And on what OS?

**Comment by hs6666** [comment]
hi, yes it happened after the last update (todays update, same issue)

i'm running it on docker on latest debian 

(Portainer is installed, which showed me the logs)

**Comment by xavier-hernandez** [comment]
Debian 11?

I just ran it on that and received no error.


root@----:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

GOAN v1.0.9


NGINX BASIC AUTH
-------------------------------
None

LOADING ACTIVE PROXY LOGS
-------------------------------
Filename: /opt/log/proxy-host-4_access.log | Read = yes
Found (1) proxy logs...

SKIP ARCHIVED LOGS
-------------------------------
False
No archived logs found at /opt/log...

EXCLUDE IPS
-------------------------------
3.2.2.48

DEBUG
-------------------------------
ON

RUN MAIN GOACCESS
Daemonized GoAccess: 25

**Comment by xavier-hernandez** [comment]
@Just5KY thanks!

**Comment by hs6666** [comment]
hi, on x86 (docker running in a VM)
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

tried restarting container, also attached log file showing error frequency

if i go into "inspect" in portainer get the following detailed output....

*******************************************************
{
    "AppArmorProfile": "",
    "Args": [
        "/goan/start.sh"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "sh",
            "/goan/start.sh"
        ],
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PGID=1000",
            "PUID=1000",
            "TZ=Europe/London"
        ],
        "ExposedPorts": {
            "7880/tcp": {}
        },
        "Hostname": "ab1043e1ff25",
        "Image": "xavierh/goaccess-for-nginxproxymanager:develop",
        "Labels": {
            "com.docker.compose.config-hash": "bfd95299090d3e4e1b11dd09f72a5644aa45a37a9e2a24b016e6f84979354dd0",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "goaccess",
            "com.docker.compose.project.config_files": "/data/compose/2/docker-compose.yml",
            "com.docker.compose.project.working_dir": "/data/compose/2",
            "com.docker.compose.service": "goaccess",
            "com.docker.compose.version": "1.27.4"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/opt/log": {}
        },
        "WorkingDir": "/goan"
    },
    "Created": "2022-06-06T17:12:44.398882666Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/5b4bb014ad174466a3d71245e127340e0c45b761547a6a3dfa5747f75d4cdfce-init/diff:/var/lib/docker/overlay2/687608be31fa3be74f5fd95b7b403f9b92a7ad35c9acf2cecce2fd3a587cdf22/diff:/var/lib/docker/overlay2/4fdcf68f2365205f43b46f6c0c1594548d266a967df866f058bb993cfa894fbf/diff:/var/lib/docker/overlay2/c1d774d79f9d4e018a48edc9d5c34eb0626341ddf7924c4256ef5346389ce7d6/diff:/var/lib/docker/overlay2/76af47d33030329e0efb75a987bee1baa02d96790bb320226dd6e83c667d2e87/diff:/var/lib/docker/overlay2/8562ae8f6ae815d241b5b945df1ec326ff00312e583899966e458d2b585dec4a/diff:/var/lib/docker/overlay2/d2838e07c9dd3f3eab5701ede01de5a1a829532223c86822f6bdb0de851880ab/diff:/var/lib/docker/overlay2/b403c3fecf9a20e277a4a22208ba4dce20f796532df65c90d7240dc63563c079/diff:/var/lib/docker/overlay2/54b859a633a20aa6009af2568b67d87fd60e686da3615e3773c6de1ccea401e8/diff:/var/lib/docker/overlay2/63b5037f4ac2f2630226babdb409a89e020953eb39a250b87854324e5e6e2d47/diff:/var/lib/docker/overlay2/54285913bacfd5cf511aedc8d36c7a3a9365a335ed77b11d96f14e75cc4b6a30/diff",
            "MergedDir": "/var/lib/docker/overlay2/5b4bb014ad174466a3d71245e127340e0c45b761547a6a3dfa5747f75d4cdfce/merged",
            "UpperDir": "/var/lib/docker/overlay2/5b4bb014ad174466a3d71245e127340e0c45b761547a6a3dfa5747f75d4cdfce/diff",
            "WorkDir": "/var/lib/docker/overlay2/5b4bb014ad174466a3d71245e127340e0c45b761547a6a3dfa5747f75d4cdfce/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/home/user/nginx-proxy-manager/data/logs:/opt/log"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "private",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "default",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "7880/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "7880"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": []
    },
    "HostnamePath": "/var/lib/docker/containers/47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8/hostname",
    "HostsPath": "/var/lib/docker/containers/47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8/hosts",
    "Id": "47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8",
    "Image": "sha256:c856700beddefd272055c165078bda48d2cac9aee4a3bbb07d16415b0a144cec",
    "LogPath": "/var/lib/docker/containers/47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8/47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/opt/log",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/home/user/nginx-proxy-manager/data/logs",
            "Type": "bind"
        }
    ],
    "Name": "/goaccess",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "13f54aa1352d7d33f67847867f7b5f9ef4f0e18ec0e03dee69a08f0ef74609c5"
            }
        },
        "Ports": {},
        "SandboxID": "f670dc86015895f1c5c546508c661029ea6c35b52b6e4e42f0ea3fda9241c133",
        "SandboxKey": "/var/run/docker/netns/f670dc860158",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "sh",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 20,
            "ResourceId": "47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/47b9f66e3beffd347892bfc6420bf388992f466b0b6cdcb23689d94440202fa8/resolv.conf",
    "RestartCount": 11,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 2,
        "FinishedAt": "2022-06-06T21:16:13.31487837Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": true,
        "Running": true,
        "StartedAt": "2022-06-06T21:16:13.241248429Z",
        "Status": "restarting"
    }
}
***********************************************

[_goaccess_logs.txt](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/files/8848070/_goaccess_logs.txt)

**Comment by xavier-hernandez** [comment]
This line below is wrong. It should be bash. I double checked the Dockerfilein the repo and it says bash. 

sh",
"/goan/start.sh"
],

**Comment by rtorchia** [comment]
Just updated my docker container from Portainer with no issues. (Ubuntu LTS 22.04 server as VM under Proxmox). I just updated the stack I have, it stopped the container, and updated without issues.
Here is my stack in Portainer:

```
version: '3'
  
services:
  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: unless-stopped
    environment:
        - TZ=America/Toronto
        - SKIP_ARCHIVED_LOGS=False #optional   
        - BASIC_AUTH=True #optional
        - BASIC_AUTH_USERNAME=secret #optional
        - BASIC_AUTH_PASSWORD=secret #optional   
        - EXCLUDE_IPS=127.0.0.1  #optional - comma delimited list
    ports:
        - '7880:7880'
    volumes:
        - /home/torchia/nginx-proxy-manager/data/logs:/opt/log
```

**Comment by xavier-hernandez** [comment]
@hs6666 try to pull the latest. Maybe I had a bug a past build.

**Comment by hs6666** [comment]
I usually update via portainer, tried via console, got message that its already upto date

i normally update on every release, only happened on the last update before this latest one

Can i update manually "to bash" via any config update or better to totally removed the container, and recreate form scratch?

thanks

**Comment by xavier-hernandez** [comment]
@hs6666 an easy thing would be to switch to the latest tag and you should get the new image. I think your using develop.

**Comment by Just5KY** [comment]
use something like Watchtower or Pullio to pull and update your docker containers automatically and also prune old images 
just make sure you read their documentation on how to set them up properly

**Comment by hs6666** [comment]
i prefer manual updates, so usually use portainer's "recreate" option whilst selecting the option to pull latest image... then manually delete the old image through portainer

I can't see a way inside portainer of renaming the image associated with a existing container from develop to latest.

I assume if i just run "docker pull xavierh/goaccess-for-nginxproxymanager:latest" from console I will just end up with a second goaccess container?

**Comment by hs6666** [comment]
oh ok, on my side, using portainer recreate, it gives a successfull message....

i initially created it with docker-compose and yaml file

I think I'll totally delete the container and this time fire it up within portainer

**Comment by hs6666** [comment]
yes, i gave up trying to get it to work....
