### ISSUE TITLE
custom can't work

### ISSUE THREAD

**Issue by andyoulovexy** [xavier-hernandez/goaccess-for-nginxproxymanager#78]
![image](https://user-images.githubusercontent.com/38940994/182827646-43800108-c616-4901-bf55-6c2da378d126.png)
![image](https://user-images.githubusercontent.com/38940994/182827710-95023607-e020-482d-94d8-f5bfcc18faaf.png)
![image](https://user-images.githubusercontent.com/38940994/182827809-94e5d35d-ab98-4f6d-8220-c61f4175ea0c.png)

**Comment by xavier-hernandez** [comment]
@andyoulovexy that error usually means that it can't read the log files. Can you verify in the container by trying to access the mapped volume? Also, it doesn't look like you provided the entire configuration file. If you can provide the whole thing that would be great.

**Comment by xavier-hernandez** [comment]
Closing this for now... open again if you want me to work on it.
