### ISSUE TITLE
Multiple Log Files in goaccess.conf

### ISSUE THREAD

**Issue by CKranebitter** [xavier-hernandez/goaccess-for-nginxproxymanager#83]
Thanks for building this great tool. Appreciate it.
Sorry if its a dumb question. My log-directory consists of multiple files depending on the service e.g.:

1. vnstat-access.log
2. prometheus-access.log

Is it possible to wildcard the `log-file`-directive in the goaccess.conf-File?
I tried with asterisk but no luck.

**Comment by xavier-hernandez** [comment]
@CKranebitter sorry no, as far as my understanding goes you need to explicitly list each file. Are all the files you have going to using one log type?

I'm happy to try and write something if I can.

**Comment by CKranebitter** [comment]
Ah. Ok. Then I list them. No problem.
They are all standard Nginx. Guess its some sort of combined NCSA:

`10.0.0.2 - - [16/Aug/2022:19:57:07 +0200] "GET / HTTP/1.1" 200 989 "-" "Uptime-Kuma/1.17.1"`

**Comment by xavier-hernandez** [comment]
@CKranebitter  if you want I can add a generic "NCSA Combined Log Format" log type that would do the *.log for you and read everything in the directory. 

LOG_TYPE = NCSA_COMBINED

**Comment by CKranebitter** [comment]
That would be really great. 
Much appreciate it.

**Comment by xavier-hernandez** [comment]
@CKranebitter would it be possible for you to supply some sample logs? Thanks.

**Comment by CKranebitter** [comment]
Sure. How do you want it?

**Comment by xavier-hernandez** [comment]
@CKranebitter you can use pastebin and just send a sample data set. Make sure to choose burn after read if it contains sensitive info.

**Comment by CKranebitter** [comment]
There you go:
https://pastebin.com/bLpKTDu5
https://pastebin.com/Jmku47X5
https://pastebin.com/bPtGeH2f

**Comment by CKranebitter** [comment]
kuma-access.log
radicale-access.log
snapit-access.log

**Comment by xavier-hernandez** [comment]
@CKranebitter got it. I'll let you know when I have something.

**Comment by CKranebitter** [comment]
Awesome. Thanks in advance.

**Comment by xavier-hernandez** [comment]
@CKranebitter looks like kuma and snapit are NCSA Combined. Not sure what radicale yet is. Will let you know.

**Comment by xavier-hernandez** [comment]
@CKranebitter I was wrong and was using the wrong format. I've updated the develop branch with the changes and the container. Make sure the log type is NCSA_COMBINED. You can look at the readme: https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/tree/develop. The code will add all files *.log.

docker pull xavierh/goaccess-for-nginxproxymanager:develop

Let me know how it works out.

**Comment by CKranebitter** [comment]
Thanks for this fast adjustement – Works great!
I had an issue on my side.
The directory I specify looks like this for my 3 services:

- -----/opt/log
- --------------kuma-access.log
- --------------kuma-error.log
- --------------snapit-access.log
- --------------snapit-error.log
- --------------radicale-access.log
- --------------radicale-error.log

So wildcarding *.logs also parses the error-logs, which have a different format.
I adjusted `resources/scripts/logs/ncsa_combined.sh` like this:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/63287042/185362571-1f10fcb0-b371-46a2-b8e0-9ec95026801f.png">

Maybe you want to include `access` somewhere to ensure that only those kind of files get parsed.
Thanks again. Really great tool.

**Comment by xavier-hernandez** [comment]
@CKranebitter  I updated the container again with a new parameter LOG_FILES. Can you try that and see if it works for you?

- LOG_FILES="*access.log"

**Comment by CKranebitter** [comment]
YES! This works.

Maybe you want to consider renaming the environmental-variable to something like `LOG_FILE_PATTERN` or something. `LOG_FILES`seems a bit generic. Just my 2 cents.
Nevertheless. Really big thanks for your time and dedication getting this to work.

**Comment by xavier-hernandez** [comment]
@CKranebitter makes sense. I'll change it.

**Comment by xavier-hernandez** [comment]
@CKranebitter the flag is now called LOG_TYPE_FILE_PATTERN to match the other pratemeter. You can pull again the develop or latest to get the most recent changes.
