### ISSUE TITLE
Doesnt´t work with Nginx Proxy Manager

### ISSUE THREAD

**Issue by dramosbarajas** [xavier-hernandez/goaccess-for-nginxproxymanager#85]
Hello, 

I have installed on a Raspberry pi4 the image with the LOG_TYPE=NPM for a reverse proxy service that I have running with the jc21/nginx-proxy-manager container and I have the following problem. 

OFF
RUN NPM GOACCESS
 [SETTING UP STORAGE /opt/log/proxy-host-4_access.log] {0} @ {0/s}
Cleaning up resources...
==27== GoAccess - version 1.6.2 - Aug 18 2022 21:53:55
==27== Config file: /goaccess-config/goaccess.conf
==27== https://goaccess.io - <hello@goaccess.io>
==27== Released under the MIT License.
==27==
==27== FILE: /opt/log/proxy-host-1_access.log
==27== Parsed 10 lines producing the following errors:
==27==
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '92.168.1.1 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27== Token '8.29.164.31 - - [20/Aug/2022' doesn't match specifier '%d'
==27==
==27== Format Errors - Verify your log/date/time format
GOAN v1.1.4
NGINX SETUP...
NGINX BASIC AUT

The container keeps restarting, any help?

Thanks

**Comment by Just5KY** [comment]
@dramosbarajas post the following
- docker-compose for Goaccess and NPM.
- a sample log file from NPM (you can hide the IPs)

I am also running on Pi4, mine runs normally, no errors.

**Comment by dramosbarajas** [comment]
Hi @Just5KY 

Add files. 

[goaccess.txt](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/files/9386995/goaccess.txt)
[NPM_access_log.txt](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/files/9386996/NPM_access_log.txt)
[npm.txt](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/files/9386997/npm.txt)

thanks!!

**Comment by Just5KY** [comment]
@dramosbarajas which log file is this?

My `proxy-host-15_access.log` looks like this

```log
[20/Aug/2022:02:04:45 +0000] - - 302 - GET https npm.justsky.in "/" [Client 144.24.x.x] [Length 142] [Gzip -] [Sent-to 192.168.0.107] "Links (2.22; Linux X86_64; GNU C; text)" "-"
[20/Aug/2022:02:19:48 +0000] - 200 200 - GET https npm.justsky.in "/robots.txt" [Client 77.88.5.160] [Length 741] [Gzip -] [Sent-to 192.168.0.107] "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)" "-"
[20/Aug/2022:02:19:51 +0000] - - 302 - GET https npm.justsky.in "/" [Client 77.88.5.160] [Length 142] [Gzip -] [Sent-to 192.168.0.107] "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)" "-"
[20/Aug/2022:02:20:50 +0000] - - 302 - GET https npm.justsky.in "/" [Client 77.88.5.24] [Length 142] [Gzip -] [Sent-to 192.168.0.107] "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)" "-"
```

`proxy-host-38_error.log` looks like this

```log
2022/08/19 15:58:23 [warn] 395#395: *782272 a client request body is buffered to a temporary file /tmp/nginx/body/9/78/0000376789, client: 10.244.67.0, server: justsky.in, request: "POST /ghost/api/admin/themes/upload/ HTTP/2.0", host: "justsky.in", referrer: "https://justsky.in/ghost/"
```

- Can you confirm if your NPM is up-to-date?

**Comment by Just5KY** [comment]
Your logs are in Apache Combined log format
https://www.sumologic.com/blog/apache-access-log/

Let's wait for @xavier-hernandez to take a look

**Comment by dramosbarajas** [comment]
HI @Just5KY 

My proxy-host-1_error.log  looks like this 

2022/08/20 09:20:21 [warn] 309#309: *3 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 88.29.xxx.xxx, server: web.filemon.duckdns.org, request: "GET /wp-content/uploads/2022/03/cat_ropa-1400x681.webp HTTP/2.0", upstream: "http://192.168.1.245:8100/wp-content/uploads/2022/03/cat_ropa-1400x681.webp", host: "web.duckdns.org", referrer: "https://web.duckdns.org/"

My proxy-host-1_access.log is diferente than you, NPM updated
217.61.xxx.xxx - - [20/Aug/2022:11:51:20 +0000] "POST /wp-login.php HTTP/1.1" 200 3095 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"


NPM is updated 

"NODE_ENV=production",
                "NPM_BUILD_VERSION=2.9.18",
                "NPM_BUILD_COMMIT=cce73be",
                "NPM_BUILD_DATE=2022-03-31 05:46:34 UTC"

I don´t understand... Thanks

**Comment by xavier-hernandez** [comment]
@dramosbarajas, @Just5KY is right. Your log files do not seem to be out of the box NGINX PROXY MANAGER logs. Did you do any additional customizations?

I **_THINK_** this is the default
[$time_local] $upstream_cache_status $upstream_status $status - $request_method $scheme $host "$request_uri" [Client $remote_addr] [Real-ip $http_cf_connecting_ip] [Length $body_bytes_sent] [Gzip $gzip_ratio] [Sent-to $server] "$http_user_agent" "$http_referer"'

I'm also running 2.9.18.

**Comment by dramosbarajas** [comment]
Hi, I don't remember doing any additional customisation, as I have it in a development environment I'm going to install it from 0 and test it. 

I will keep you posted. 

Thanks for all @xavier-hernandez @Just5KY

**Comment by xavier-hernandez** [comment]
@dramosbarajas, cool yeah keep us posted.

**Comment by dramosbarajas** [comment]
Reinstalling NPM, everything works correctly. 

Thanks for the support, I deeply regret not having tested this before opening the issue.

**Comment by xavier-hernandez** [comment]
@dramosbarajas no problem. Glad everything is working.
