### ISSUE TITLE
Container stop on Fatal error when Autostart and need to be manually started .

### ISSUE THREAD

**Issue by masterwishx** [xavier-hernandez/goaccess-for-nginxproxymanager#86]
Thanks for cool container again.

on Autostart when Unraid server boot or start after Appdata Backup the container stop on Fatal error .
but if then manualy start it its OK.

after Added LOG_TYPE=NPM nothing changed .

![image](https://user-images.githubusercontent.com/28630321/185778632-ec31278a-0e2e-4c48-a8da-fa81c580c7c0.png)

**Comment by masterwishx** [comment]
just added "--restart=unless-stopped" to avoid the issue on autostart for now 
if someone also having the issue in unraid please confirm

**Comment by xavier-hernandez** [comment]
@masterwishx can you switch to the develop branch / container and see if this issue has been fixed ?

**Comment by masterwishx** [comment]
@xavier-hernandez  
> can you switch to the develop branch
OK i can, Thanks

**Comment by masterwishx** [comment]
@xavier-hernandez 
Confirm, NO Error on Develop version , also tryed after reboot ...

**Comment by xavier-hernandez** [comment]
Pushed out the latest version to production. 
[gh pr checkout 94](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/pull/94)
