### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by s1oz** [xavier-hernandez/goaccess-for-nginxproxymanager#99]
How can I achieve the same effect as in the [link?](https://github.com/allinurl/goaccess/issues/1043#issuecomment-372111348)
`-e LANG=zh_CN` or `-e LANG=zh_CN.UTF-8` or `-e LC_ALL=zh_CN.UTF-8` does not take effect, still cannot display Chinese

**Comment by xavier-hernandez** [comment]
@s1oz I will look into this.

**Comment by s1oz** [comment]
thank you for your reply @xavier-hernandez

**Comment by xavier-hernandez** [comment]
@s1oz the develop version has been updated to support language localizations, docker pull xavierh/goaccess-for-nginxproxymanager:develop 

Can you test it out?

**Comment by s1oz** [comment]
@xavier-hernandez thank you very much for your help！

`-e LC_ALL=zh_CN.UTF-8`Chinese successfully displayed
